title: AMU's Notes
description: My Personal blog
author: AMU
github: https://github.com/amuuu
about: I make stuff (sound tools, music, games, etc.)
disqus_shortname: amunotes
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-instagram
      link: "https://instagram.com/amuexpress"
    - icon: fa-twitter
      link: "https://twitter.com/sudoamu"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/amirreza-amouie"
    - icon: fa-spotify
      link: "https://spoti.fi/2kNt827"
    - icon: fa-bandcamp
      link: "https://amuuu.bandcamp.com"
    - icon: fa-github
      link: "https://github.com/amuuu"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://amuuu.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
